import type { Metadata } from "next";
import { Josefin_Slab } from "next/font/google";
import "./globals.css";

const inter = Josefin_Slab({
  subsets: ["latin"],
  display: "swap",
  fallback: ["sans-serif", "Arial"],
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
